Repository m-lab/k8s-support, pull requests merged in 2018-05, with the labels that each got.

#30 Save binaries in epoxy images rather than during the ePoxy action
  node/node_k8s_setup.sh
  node/push_setup.sh
Labels: Sprint 9, Task

#35 Add the k8s master to the epoxy-extension network by default
  cloud/setup_cloud_k8s_master.sh
Labels: Sprint 10

#36 Add version in token service URL
  cloud/token_server/main.go
Labels: Sprint 10, Task
