Repository m-lab/k8s-support, pull requests merged in 2018-06, with the labels that each got.

#37 Add Dockerfile to build token_server container
  cloud/token_server/Dockerfile
Labels: Sprint 10, Task

#39 Networks now work (in alpha form)
  cloud/k8s/multus.yml
  cloud/k8s/network-cloud.yml
  cloud/k8s/network-common.yml
  cloud/k8s/network-crd.yml
  cloud/k8s/network-node.yml
  cloud/setup_cloud_k8s_master.sh
  cloud/test-pod.yml
  node/node_k8s_setup.sh
  node/push_setup.sh
  node/shim.sh
Labels: Sprint 11, Task

#38 Start k8s-token-server when installing k8s master
  cloud/setup_cloud_k8s_master.sh
  cloud/token_server/main.go
Labels: Sprint 11

#41 Uses the GCP project as an input parameter to the script.
  node/node_k8s_setup.sh
Labels: Sprint 11

#51 Make running the setup script easier, in response to actual user experience.
  cloud/README.md
  cloud/setup_cloud_k8s_master.sh
  node/node_k8s_setup.sh
Labels: 1, Sprint 11, Story

#52 Creates a new cloud VM and joins it to the cluster.
  cloud/allocate_new_cloud_node.sh
Labels: 2, Sprint 11, Story

#56 Make the internal network work.
  cloud/allocate_new_cloud_node.sh
  cloud/k8s/multus.yml
  cloud/k8s/network-common.yml
  cloud/setup_cloud_k8s_master.sh
  cloud/test-pod.yml
  node/node_k8s_setup.sh
Labels: 2, Sprint 11, Story
